core/urls.py
from django.urls import path

from .views import (
    about,
    booking_view,
    brand,
    brand_update,
    car_details_view,
    create_brand,
    delete_brand,
    home,
    contact,
    search,
    product_brand,
    service,
    testimonials,
)

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('service/', service, name='service'),
    path('car-details/<str:slug>', car_details_view, name='car-details'),
    path('booking/<slug>/', booking_view, name='booking'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('search/', search, name='search'),
    path('post-testimonials', testimonials, name='post-testimonials'),
    path('brand', brand, name='brand'),
    path('create_brand', create_brand, name='create_brand'),
    path('brand_update/<int:id>', brand_update, name='brand_update'),
    path('delete_brand/<int:id>', delete_brand, name='delete_brand'),
    path('product/brand/<str:slug>', product_brand, name='product_brand'),
]

fastcars/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('account/', include("account.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

service/urls.py
# from django.urls import path
# from .views import service

# app_name = 'service'

# urlpatterns = [
#     path('', service, name='service'),
# ]

service/models.py
# from django.db import models
# from datetime import datetime
# from django.core.validators import FileExtensionValidator
# from multiselectfield import MultiSelectField
# from account.models import User
# from django.utils.text import slugify
# from django.urls import reverse
# # Create your models here.


# class Brand(models.Model):
#     brand = models.CharField(max_length=250, unique=True)
#     brand_image = models.ImageField(upload_to="BrandImages/")
#     date_created = models.DateTimeField(auto_now=True)
#     slug = models.SlugField(max_length=100, unique=True, blank=True)

#     class Meta:
#         verbose_name = ("Brand")
#         verbose_name_plural = ("Brands")

#     def __str__(self):
#         return self.brand

#     def save(self, *args, **kwargs):
#         slug = self.brand
#         self.slug = slugify(slug, allow_unicode=True)
#         super().save(*args, **kwargs)

#     def get_absolute_url(self):
#         return reverse("core:product_brand", kwargs={"pk": self.pk})


# class Car(models.Model):
#     state_choice = (
#         ('NI', 'Niger'),
#         ('BO', 'Borno '),
#         ('TA', 'Taraba'),
#         ('KD', 'Kaduna'),
#         ('BA', 'Bauchi'),
#         ('YO', 'Yobe'),
#         ('ZA', 'Zamfara'),
#         ('AD', 'Adamawa'),
#         ('KW', 'Kwara'),
#         ('KE', 'Kebbi'),
#         ('BE', 'Benue'),
#         ('PL', 'Plateau'),
#         ('KO', 'Kogi'),
#         ('OY', 'Oyo'),
#         ('NA', 'Nasarawa'),
#         ('SO', 'Sokoto'),
#         ('KT', 'Katsina'),
#         ('JI', 'Jigawa'),
#         ('CR', 'Cross River'),
#         ('KN', 'Kano'),
#         ('GO', 'Gombe'),
#         ('ED', 'Edo'),
#         ('DE', 'Delta'),
#         ('OG', 'Ogun'),
#         ('ON', 'Ondo'),
#         ('RI', 'Rivers'),
#         ('BY', 'Bayelsa'),
#         ('OS', 'Osun'),
#         ('FC', 'Fct'),
#         ('EN', 'Enugun'),
#         ('AK', 'Akwa Ibom'),
#         ('EK', 'Ekit'),
#         ('AB', 'Abia'),
#         ('EB', 'Ebonyi'),
#         ('IM', 'Imo'),
#         ('AN', 'Anambra'),
#         ('LA', 'Lagos'),
#     )

#     features_choices = (
#         ('Cruise Control', 'Cruise Control'),
#         ('Audio Interface', 'Audio Interface'),
#         ('Airbags', 'Airbags'),
#         ('Air Conditioning', 'Air Conditioning'),
#         ('Seat Heating', 'Seat Heating'),
#         ('Alarm System', 'Alarm System'),
#         ('ParkAssist', 'ParkAssist'),
#         ('Power Steering', 'Power Steering'),
#         ('Reversing Camera', 'Reversing Camera'),
#         ('Direct Fuel Injection', 'Direct Fuel Injection'),
#         ('Auto Start/Stop', 'Auto Start/Stop'),
#         ('Wind Deflector', 'Wind Deflector'),
#         ('Bluetooth Handset', 'Bluetooth Handset'),
#     )

#     door_choices = (
#         ('2', '2'),
#         ('3', '3'),
#         ('4', '4'),
#         ('5', '5'),
#         ('6', '6'),
#     )

#     year_choice = []
#     for r in range(2000, (datetime.now().year + 1)):
#         year_choice.append((r, r))

#     car_name = models.CharField(verbose_name='car_title', max_length=200)
#     brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True)
#     city = models.CharField(max_length=200)
#     state = models.CharField(max_length=10, choices=state_choice)
#     color = models.CharField(max_length=200)
#     model = models.CharField(max_length=200)
#     year = models.IntegerField(('Year'), choices=year_choice)
#     condition = models.CharField(max_length=200)
#     price = models.PositiveIntegerField()
#     description = models.TextField()
#     car_photo = models.ImageField(validators=[FileExtensionValidator(
#         ['jpg', 'jpeg'])], upload_to='cars_images')
#     car_photo_1 = models.ImageField(validators=[FileExtensionValidator(
#         ['jpg', 'jpeg'])], upload_to='cars_images', blank=True)
#     car_photo_2 = models.ImageField(validators=[FileExtensionValidator(
#         ['jpg', 'jpeg'])], upload_to='cars_images', blank=True)
#     body_style = models.CharField(max_length=200)
#     miles = models.PositiveIntegerField()
#     doors = models.CharField(choices=door_choices, max_length=10)
#     passengers = models.PositiveIntegerField()
#     milage = models.PositiveIntegerField()
#     fuel_type = models.CharField(max_length=50)
#     is_latest = models.BooleanField(default=False)
#     is_booked = models.BooleanField(default=False)
#     created_date = models.DateField(default=datetime.now, blank=True)
#     slug = models.SlugField(max_length=500, unique=True, blank=True)

#     def __str__(self):
#         return self.car_name

#     def save(self, *args, **kwargs):
#         slug = self.brand
#         if not self.slug:
#             self.slug = slugify(slug, allow_unicode=True)
#         super().save(*args, **kwargs)

#     def get_absolute_url(self):
#         return reverse("core:product", kwargs={'id': self.id})


# class Booking(models.Model):
#     state_choice = (
#         ('NI', 'Niger'),
#         ('BO', 'Borno '),
#         ('TA', 'Taraba'),
#         ('KD', 'Kaduna'),
#         ('BA', 'Bauchi'),
#         ('YO', 'Yobe'),
#         ('ZA', 'Zamfara'),
#         ('AD', 'Adamawa'),
#         ('KW', 'Kwara'),
#         ('KE', 'Kebbi'),
#         ('BE', 'Benue'),
#         ('PL', 'Plateau'),
#         ('KO', 'Kogi'),
#         ('OY', 'Oyo'),
#         ('NA', 'Nasarawa'),
#         ('SO', 'Sokoto'),
#         ('KT', 'Katsina'),
#         ('JI', 'Jigawa'),
#         ('CR', 'Cross River'),
#         ('KN', 'Kano'),
#         ('GO', 'Gombe'),
#         ('ED', 'Edo'),
#         ('DE', 'Delta'),
#         ('OG', 'Ogun'),
#         ('ON', 'Ondo'),
#         ('RI', 'Rivers'),
#         ('BY', 'Bayelsa'),
#         ('OS', 'Osun'),
#         ('FC', 'Fct'),
#         ('EN', 'Enugun'),
#         ('AK', 'Akwa Ibom'),
#         ('EK', 'Ekit'),
#         ('AB', 'Abia'),
#         ('EB', 'Ebonyi'),
#         ('IM', 'Imo'),
#         ('AN', 'Anambra'),
#         ('LA', 'Lagos'),
#     )
#     city = models.CharField(max_length=200)
#     pick_up_location = models.CharField(max_length=10, choices=state_choice)
#     drop_off_location = models.CharField(max_length=10, choices=state_choice)
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     car = models.OneToOneField(Car, on_delete=models.CASCADE)
#     booking_date = models.DateTimeField(auto_now_add=True)
#     To_agree = models.BooleanField(default=False, verbose_name='Car is Booked')

#     def __str__(self):
#         return f"{self.user.first_name} booked {self.car.car_name} from {self.pick_up_location} to {self.drop_off_location}"

service/views.py
# from pyexpat.errors import messages
# from django.shortcuts import render, get_object_or_404, redirect
# from .models import Car, Brand
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# # from .forms import BrandForm, BookingForm
# from django.db.models import Q
# from django.contrib.auth.decorators import login_required


# def service(request):
#     cars = Car.objects.all()
#     p = Paginator(cars, 2)
#     page = request.GET.get('page')
#     car_pages = p.get_page(page)

#     context = {
#         'cars': car_pages,
#     }
#     return render(request, 'service.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %} {% endblock %}
    <!-- master stylesheet -->
    <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    
    <!-- Responsive stylesheet -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-touch-icon.png' %}" />
    <link rel="icon" type="image/png" href="{% static 'images/favicon/favicon-32x32.png' %}" sizes="32x32" />
    <link rel="icon" type="image/png" href="{% static 'images/favicon/favicon-16x16.png' %}" sizes="16x16" />
</head>

<body>
    <div class="boxed_wrapper">
        <!--Start Preloader -->
        <!-- <div class="preloader"></div> -->
        <h6>{% include 'partial/messages.html' %}</h6>
        {% include "navbar.html" %}
        <!--End Preloader -->
        {% block content %}
        
        {% endblock content %}
    </div>
    <!--Scroll to top-->
    <div class="scroll-to-top scroll-to-target" data-target="html">
        <span class="fa fa-chevron-circle-up"></span>
    </div>
    {% include "footer.html" %} 
    {% include "scripts.html" %}
</body>

</html>

templates/booking.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}
{% block head_title %}Book Car |Fast Cars{% endblock  %}
{% block content %}

<!--Start breadcrumb area-->
<section
  class="breadcrumb-area"
  style="background-image: url(/static/images/brand_banner.jpg)"
>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="breadcrumbs">
          <h1 style="color: black;">Booking</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="breadcrumb-botton">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="left">
            <li><a href="{% url 'core:home' %}">Home</a></li>
            <li><i class="fa fa-angle-right" aria-hidden="true"></i></li>
            <li class="active">Booking</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
<!--End breadcrumb area-->

<!-- booking design -->
<section id="project-single-area">
    <div class="container">
        <div class="row py-5">
            <div class="col-sm-4 col-md-4 my-2">
                <div class="card" style="width: 100%;">
                    <img src="{{car.car_photo.url}}" class="card-img-top" alt="...">
                    <h3>{{car.car_name|capfirst}}</h3>
                </div>
            </div>
            <!-- second -->
            <div class="col-sm-4 col-md-4 my-2">
                <div class="card shadow bg-dark text-warning fw-bolder" style="width: 100%;">
                    <div class="card-header">
                        {{car.brand}}
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Model : {{car.model|capfirst}}</li>
                        <li class="list-group-item">Color : {{car.color|capfirst}}</li>
                        <li class="list-group-item">Condition : {{car.condition|capfirst}}</li>
                        <li class="list-group-item">Body style : {{car.body_style|capfirst}}</li>
                        <li class="list-group-item">Miles : {{car.miles|capfirst}}</li>
                        <li class="list-group-item">Doors : {{car.doors|capfirst}}</li>
                        <li class="list-group-item">No of passenger : {{car.passengers|capfirst}}</li>
                        <li class="list-group-item">Fuel Type : {{car.fuel_type|capfirst}}</li>
                        <li class="list-group-item">Doors : {{car.doors|capfirst}}</li>
                    </ul>
                    <div class="card-footer shadow bg-dark text-warning fw-bolder text-center" style="background-color: black; color: white; padding: 20px;">
                        Book For >>> ${{car.price|intcomma|capfirst}}
                    </div>
                </div>
    
                <!--  -->
                
            </div>
            <div class="col-sm-4 col-md-4 my-2">
    
                <div class="form shipping-info">
                    <div class="sec-title pdb-50">
                        <h1>Booking Info</h1>
                        <span class="border"></span>
                    </div>
                    <form action="" method="POST">
                        <div class="row">
    
                            {% csrf_token %}
            
                            {{ form|crispy }}
                            <input type="submit" value="Book" class="btn text-center btn-primary btn-lg">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!--  -->

{% endblock content %}

templates/brand.html
{% extends "base.html" %}
{% load static %}
{% block head_title %}Brands |Fast Cars{% endblock  %}
{% block content %}

<!--Start breadcrumb area-->     
<section class="breadcrumb-area" style="background-image: url(/static/images/brand_banner.jpg);">
	<div class="container">
	    <div class="row">
	        <div class="col-md-12">
	            <div class="breadcrumbs">
	                <h1 style="color: black;">Brands</h1>
	            </div>
	        </div>
	    </div>
	</div>
    <div class="breadcrumb-botton">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="left">
                        <li><a href="{% url 'core:home' %}">Home</a></li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i></li>
                        <li class="active">Brands</li>
                    </ul>   
                </div>
            </div>
        </div>
    </div>
</section>
<!--End breadcrumb area--> 


<!--Start cart area-->
<section class="cart-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-7 col-sm-7 col-xs-12">
                <div class="sidebar-wrapper">
                    <!--Start single sidebar-->
                    <div class="single-sidebar">
                        <form class="search-form" action="{% url 'core:create_brand' %}" method="POST">
                            {% csrf_token %}
							<input type="text" name="brand" placeholder="Create new brand">
							<button type="submit"><i class="fa fa-plus" aria-hidden="true"></i></button>
						</form>
                    </div>
            </div>
        </div>
        {% if brands %}
            <div class="col-md-12">
                <div class="table-outer">
                    <table class="cart-table">
                        <thead class="cart-header">
                            <tr>
                                <th class="prod-column">S/N</th>
                                <th>&nbsp;</th>
                                <th class="prod-column">Brand Name</th>
                                <th>&nbsp;</th>
                                <th class="prod-column">Update</th>
                                <th>&nbsp;</th>
                                <th class="prod-column">Delete</th>
                                <th>&nbsp;</th>

                            </tr>    
                        </thead>
                        <tbody>
                            {% for brand in brands %}
                            <tr>
                                <td class="price " colspan="2" >{{ forloop.counter }}</td>
                                <td class="price " colspan="2" ><a href="{% url 'core:product_brand' brand.slug %}" style="color: grey;">{{brand.brand}}</a></td>
                                <td class="price " colspan="2" ><a href="{% url 'core:brand_update' brand.id %}" style="color: grey;"><i class="fa fa-edit"></i></a></td>
                                <td class="price " colspan="2" ><a href="{% url 'core:delete_brand' brand.id %}" style="color: grey;"><i class="fa fa-trash"></i></a></td>
                                
                            </tr>
                            {% endfor %}
                        </tbody>    
                    </table>
                </div>
            </div>
            
        <div class="row">
            <div class="col-md-12"> 
                <ul class="post-pagination text-center">
                    {% if car_pages.has_previous %}
                    <li><a href="?page={{ car_pages.previous_page_number }}"><i class="fa fa-caret-left" aria-hidden="true"></i></a></li>
                    {% else %}
                    <li title="No previous page"><a href="" style="pointer-events: none;" ><i class="fa fa-caret-left disabled" aria-hidden="true"></i></a></li>
                    {% endif %}
                    {% for i in car_pages.paginator.page_range %}
                    {% if car_pages.number == i %}
                    <li class="active"><a href="#">{{ i }}</a></li>
                    {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                    {% endfor %}

                    {% if car_pages.has_next %}
                    <li><a href="?page={{ car_pages.next_page_number }}"><i class="fa fa-caret-right" aria-hidden="true"></i></a></li>
                    {% else %}
                    <li title="No next page"><a href="" style="pointer-events: none;"><i class="fa fa-caret-right disabled" aria-hidden="true"></i></a></li>
                    {% endif %}
                </ul>
            </div> 
        </div>
        {% else %}
        <div class="text-center m-5 p-5 col-md-12">
          <div class="single-product-item">

              <h3>No Brands Available</h3>
          </div>
        </div>
        {% endif %}
    </div>
</section>         
<!--End cart area-->


{% endblock content %}

templates/brand_category.html
{% extends "base.html" %}
{% load static %}
{% block head_title %}Brands |Fast Cars{% endblock  %}
{% block content %}

<!--Start shop area-->
<section class="shop-area">
    <div class="container">
        <div class="row">
            <!--Start shop content-->
            {% if car %}
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pull-right">
                <div class="shop-content">
                    <div class="row">
                        <!--Start single product item-->
                        {% for i in car  %}
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <div class="single-product-item">
                                <div class="img-holder">
                                    <img src="{{i.car_photo.url}}" alt="Awesome Product Image" style="object-fit: cover; height: 270px;">
                                    <div class="overlay-style-one">
                                        <div class="box">
                                            <div class="content">
                                                <a href="{% url 'core:car-details' i.slug %}"><i class="fa fa-link" aria-hidden="true"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="title-holder">
                                    <div class="top clearfix">
                                        <div class="product-title pull-left">
                                            <h5>{{i.car_name}}</h5>
                                        </div>
                                       
                                    </div>
                                    <div class="product-value">
                                        <h4>${{i.price}}</h4>
                                    </div>
                                    {% if request.user.is_authenticated %}
                                    {% if i.booking.To_agree %}
                                    <hr>
                                    <h3 class="text-dark" style="text-decoration: none; color: black;">Already Booked</h3>
                                    {% else %}
                                    <div class="button">
                                        <a class="thm-btn" href="{{ car.get_booking_url }}">Book</a>
                                    </div>
                                    {% endif %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <!--End single product item-->
                        
                    </div>
                    <div class="row">
                        <div class="col-md-12"> 
                            <ul class="post-pagination text-center">
                                {% if car_pages.has_previous %}
                                <li><a href="?page={{ car_pages.previous_page_number }}"><i class="fa fa-caret-left" aria-hidden="true"></i></a></li>
                                {% else %}
                                <li title="No previous page"><a href="" style="pointer-events: none;" ><i class="fa fa-caret-left disabled" aria-hidden="true"></i></a></li>
                                {% endif %}
                                {% for i in car_pages.paginator.page_range %}
                                {% if car_pages.number == i %}
                                <li class="active"><a href="#">{{ i }}</a></li>
                                {% else %}
                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                                {% endfor %}

                                {% if car_pages.has_next %}
                                <li><a href="?page={{ car_pages.next_page_number }}"><i class="fa fa-caret-right" aria-hidden="true"></i></a></li>
                                {% else %}
                                <li title="No next page"><a href="" style="pointer-events: none;"><i class="fa fa-caret-right disabled" aria-hidden="true"></i></a></li>
                                {% endif %}
                            </ul>
                        </div> 
                    </div>
                </div>
            </div>
            <!--End shop content-->
            {% else %}
          <div class="text-center m-5 p-5">
            <div class="single-product-item">

                <h3>No Car Available in this brand category</h3>
            </div>
          </div>
          {% endif %}
        </div>
    </div>
</section>
<!--End shop area-->

{% endblock content %}

templates/brand_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Update Brand{% endblock  %}
{% block content %}
<section class="breadcrumb-area" style="background-image: url(/static/images/brand_banner.jpg);">
	<div class="container">
	    <div class="row">
	        <div class="col-md-12">
	            <div class="breadcrumbs">
	                <h1 style="color: black;">Update Brand</h1>
	            </div>
	        </div>
	    </div>
	</div>
    <div class="breadcrumb-botton">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="left">
                        <li><a href="{% url 'core:home' %}">Home</a></li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i></li>
                        <li class="active">Brands</li>
                    </ul>   
                </div>
            </div>
        </div>
    </div>
</section>
<!--End breadcrumb area--> 
<!--Start login register area-->
<section class="login-register-area">
    <div class="container">
        <div class="row">
            <h6 class='my-2 p-5'>{% include 'partial/messages.html' %}</h6>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="form register">
                    <div class="sec-title">
                        <h1>Update Brand</h1>
                        <span class="border"></span>
                    </div>
                    <div class="row">
                        <form action="" method="POST" class="p-5 bg-light shadow">
                            {% csrf_token %}
                            {{ form | crispy }}
                            <div class="btn-box mt-4 mx-auto" style="width: fit-content imo !important;">
                                <button type="submit" class="btn btn-warning rounded-3 px-4">Update Brand</button>
                            </div>
                        </form>  
                    </div>
                </div>    
            </div>
            
        </div>
    </div>
</section>
{% endblock %}

templates/navbar.html
{% load static %}
<!--Start mainmenu area-->
<section class="mainmenu-area stricky">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 clearfix">
        <!--Start logo-->
        <div class="logo pull-left">
          <a href="index.html">
            <!-- <img src="images/resources/logo.png" alt="Awesome Logo"> -->
            <h1>FAST CARS</h1>
          </a>
        </div>
        <!--End logo-->
        <!--Start mainmenu-->
        <nav class="main-menu pull-left">
          <div class="navbar-header">
            <button
              type="button"
              class="navbar-toggle"
              data-toggle="collapse"
              data-target=".navbar-collapse"
            >
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="navbar-collapse collapse clearfix">
            <ul class="navigation clearfix">
              <li><a href="{% url 'core:home' %}">Home</a></li>
              <li class="dropdown">
                <a href="" style="pointer-events: none;">Vehicles</a>
                <ul>
                  <li><a href="{% url 'core:service' %}">View All Cars</a></li>
                  {% for b ,count in brand_count %}
                  <li>
                    <a href="{% url 'core:product_brand' b.slug %}">{{b.brand}}</a>
                  </li>
                  {% endfor %}
                </ul>
              </li>
              <li><a href="{% url 'core:about' %}">About Us</a></li>
              <li><a href="{% url 'core:contact' %}">Contact Us</a></li>
              {% if request.user.is_authenticated %} 
              {% if request.user.is_staff %}
              <li class="dropdown">
                <a href="" style="pointer-events: none;">Dashboard</a>
                <ul>
                  <li>
                    <a href="\admin">Admin</a>
                  </li>
                  <li><a href="{% url 'core:brand' %}">Brands</a></li>
                </ul>
              </li>
              {% endif %}
              <li class="dropdown">
                <a href="" style="pointer-events: none;">My Account</a>
                <ul>
                  <li>
                    <a href="{% url 'edit_profile' %}">Edit Profile</a>
                  </li>
                  <li><a href="{% url 'logout' %}">Logout</a></li>
                </ul>
              </li>
              {% else %}
              <li class="dropdown">
                <a href="{% url 'register' %}">Login/Signup</a>
                <ul>
                  <li><a href="{% url 'register' %}">Register</a></li>
                  <li><a href="{% url 'login' %}">Login</a></li>
                </ul>
              </li>
              {% endif %}
            </ul>
          </div>
        </nav>
        <!--End mainmenu-->
        <!--Start mainmenu right box-->
        <div class="mainmenu-right-box pull-right">
          <div class="outer-search-box">
            <div class="seach-toggle"><i class="fa fa-search"></i></div>
            <ul class="search-box">
              <li>
                <form method ="GET" action="{% url 'core:search' %}">
                  {% csrf_token %}
                  <div class="form-group">
                    <input
                      type="search"
                      name="search"
                      placeholder="Search Here"
                      required
                    />
                    <button type="submit"><i class="fa fa-search"></i></button>
                  </div>
                </form>
              </li>
            </ul>
          </div>
        </div>
        <!--End mainmenu right box-->
      </div>
    </div>
  </div>
</section>
<!--End mainmenu area-->